---
model_params:
  name: "VanillaVAE"
  input_dim: 6
  latent_dim: 1024
  hidden_dim: 512
  num_layers: 4
  num_heads: 8
  max_seq_len: 350

data_params:
  npy_dir: "/public/home/zhangyangroup/chengshiz/keyuan.zhou/prp-dataset/filtered_curves_npy/"
  train_list: "train_list.txt"
  val_list: "val_list.txt"
  mean_xyz: [59.75617548672732, 57.48255340071842, 67.46183179563933]
  std_xyz: [114.53544376107905, 120.74113448738537, 118.6619735740254]
  train_batch_size: 256
  val_batch_size: 256
  num_workers: 4
  pin_memory: true

exp_params:
  LR: 0.0002
  ss_weight: 0.5
  weight_decay: 0.0
  scheduler_gamma: null
  kld_weight: 0.005
  kld_warmup_epochs: 5
  bond_length_weight: 0.1
  bond_angle_weight: 0.05
  manual_seed: 1265

trainer_params:
  gpus: 4
  max_epochs: 120
  strategy: "ddp"
  accelerator: "gpu"
  precision: 32
  log_every_n_steps: 20
  num_sanity_val_steps: 0
  benchmark: true
  enable_progress_bar: true

logging_params:
  save_dir: "./logs/"
  name: "VanillaVAE"
